- id: '1612554180686'
  alias: Warn if lights are disconnected
  description: If someone disables the electricity to the lights above the terras,
    the light in the living room will flash to indicate this scenario
  trigger:
  - platform: state
    entity_id: light.deur_1
    to: unavailable
  condition: []
  action:
  - device_id: e467d987ca042440cc5fb50a2e245da5
    domain: mobile_app
    type: notify
    message: Iemand heeft in de garage de stroom voor de overkapping-verlichting uitgeschakeld.
      Schakel deze weer terug in!
    title: Verkeerde knop gebruikt!
  - service: script.toggle_light_woonkamer
    data: {}
  mode: single
- id: '1612618696406'
  alias: Trash outside
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.gft
    to: Ja
  - platform: state
    entity_id: sensor.restafval
    to: Ja
  - platform: state
    entity_id: sensor.overig
    to: Ja
  - platform: state
    entity_id: sensor.papier
    to: Ja
  condition: []
  action:
  - device_id: e467d987ca042440cc5fb50a2e245da5
    domain: mobile_app
    type: notify
    message: Het afval moet buiten worden gezet! Controleer in de app welk soort afval
      naar buiten moet
    title: Afval wordt opgehaald!
  mode: single
